### ISSUE TITLE
Commits not working for feat: and doesn't ignore merge requests in visual studio code

### ISSUE THREAD

**Issue by yevon** [hazcod/semantic-commit-hook#35]
Hi! I just tried out this hook for enforcing semantic versioning, but it's not working properly for feature tags and for ignoring the merge requests.

There is a missing pipe before the "feat" tag here:

`if ! echo "$commitTitle" | grep -qE '^(?:|feat|fix|docs|style|refactor|perf|test|chore)\(?(?:\w+|\s|\-|_)?\)?:\s\w+'; then`

And for ignoring tags, it should be:

`if echo "$commitTitle" | grep -qE "Merge branch"; then`

Complete fixed code:

```
#!/usr/bin/env bash

if [ -z "$1" ]; then
	echo "Missing argument (commit message). Did you try to run this manually?"
	exit 1
fi

commitTitle="$(cat $1 | head -n1)"

# ignore merge requests
if echo "$commitTitle" | grep -qE "Merge branch"; then
	echo "Commit hook: ignoring branch merge"
	exit 0
fi

# check semantic versioning scheme
if ! echo "$commitTitle" | grep -qE '^(?:|feat|fix|docs|style|refactor|perf|test|chore)\(?(?:\w+|\s|\-|_)?\)?:\s\w+'; then
	echo "Your commit title did not follow semantic versioning: $commitTitle"
	echo "Please see https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commit-message-format"
	exit 1
fi
```

**Comment by hazcod** [comment]
Thank you @yevon , i've merged your improvements.

**Comment by earthiverse** [comment]
Using `grep (BSD grep, GNU compatible) 2.6.0-FreeBSD`, I get the error `grep: empty (sub)expression` and an exit code of `2` when running the following command

```sh
echo 'chore: test commit please ignore' | grep -qE '^(?:|feat|fix|docs|style|refactor|perf|test|chore)\(?(?:\w+|\s|\-|_)?\)?:\s\w+'
```

Removing the `|` before `feat` fixes this git hook for me.
